### ISSUE TITLE
两个Activity同Path时, 点击图标跳转问题

### ISSUE THREAD

**Issue by DYP1016** [huage2580/arouter-idea-plugin-x#1]
如果有两个module, 每个module里有一个Activity的Path是一样的, 此时在点击图标跳转, 只会跳转到其中一个Activit

能否有办法弹窗可选择跳到哪个Activity中去?

**Comment by huage2580** [comment]
可以是可以，但是为啥会同path，同path最后也是冲突的吧

**Comment by DYP1016** [comment]
应用场景有点特殊, 这两个module虽然path相同, 但实际运行时只会引入其中一个module, 目的是通过快速切换module来实现不同的功能

**Comment by huage2580** [comment]
v2.1.1支持这种场景了
