### ISSUE TITLE
能否加一个从@Route(path="xx/xx")跳转到来源的功能

### ISSUE THREAD

**Issue by sceneren** [huage2580/arouter-idea-plugin-x#2]
![image](https://user-images.githubusercontent.com/6612998/116021167-3c21c880-a67a-11eb-8ea8-dda67b246c61.png)
类似EventBus这样的功能

**Comment by huage2580** [comment]
这个插件是开源的吗，我参考下实现

**Comment by huage2580** [comment]
v2.1.2已经支持了这个功能
